blank_issues_enabled: false

contact_links:
  - name: ServBay for Windows Issues
    url: https://github.com/ServBay/ServBay-Windows-Release/issues
    about: Please submit issues for the Windows version of ServBay here.

  - name: Support Center
    url: https://support.servbay.com
    about: Please refer to our technical support documentation and help center first.